### ISSUE TITLE
can we use this in bashrc ubuntu?

### ISSUE THREAD

**Issue by adamramadhan** [topkecleon/telegram-bot-bash#38]
hello can we use this in bashrc ubuntu everytime a user login send who is login?

**Comment by danog** [comment]
of course.

**Comment by topkecleon** [comment]
Throw

`curl -s -o /dev/null "https://api.telegram.org/bot123456789:ETC/sendMessage" -F "chat_id=-987654321" -F "text=$USER has logged into $HOSTNAME"`

in /etc/profile I guess, if all you want is basic login notifications. There might be a more secure way of doing this (since the user can possibly cancel execution of bash profiles).
