### ISSUE TITLE
Отправка с прокси

### ISSUE THREAD

**Issue by mr-butch** [topkecleon/telegram-bot-bash#49]
Добрый день.
Возможна ли отправка сообщений в свете последних событий с блокировкой через прокси например?
Сообщения перестали отправляться.
С уважением.

**Comment by JuanPotato** [comment]
Hi, please speak English.
```
Sending from proxy # 49

Good afternoon.
Is it possible to send messages in the light of recent events with a proxy blocking for example?
Messages stopped sending.
Sincerely.

- Google Translate
```

A quick fix would be to add a [proxy flag](https://stackoverflow.com/a/9445516/3390376) to all the places where `curl` is called in the library. Otherwise I might be able to add it today or tomorrow. And I really really think you should be using any other library than this one. They will have much better support and performance.

**Comment by danog** [comment]
shhhhhhhhhh
