### ISSUE TITLE
globbing issue, * in a Message expands to file names?

### ISSUE THREAD

**Issue by Azat868** [topkecleon/telegram-bot-bash#70]
When sending *, internal path names are revealed. Also allows you to create an exploit

**Comment by gnadelwartz** [comment]
did you try with the latest version? 
I fixed this issue with #52 , but there may other places/reasons.

can you provide a concrete example for testing?

**Comment by Azat868** [comment]
![изображение](https://user-images.githubusercontent.com/29046741/55858000-37634800-5b77-11e9-9ad2-9fdf16c4cf8a.png)
I tried to solve the problem myself. seems wrong?

**Comment by gnadelwartz** [comment]
this was exactly the case of the Problem which is fixed by #52 , so you are using an old Version of bashbot.sh, pls update:

- go to your bashbot dir
- cp bashbot.sh bashbot.sh.org
- mkdir update
- cd update
- git clone https://github.com/topkecleon/telegram-bot-bash.git
- cd telegram-bot-bash
- cp bashbot.sh ..
- restart bashbot

If you have bashbot.sh modified you have to fix reapply your changes ...

**Comment by gnadelwartz** [comment]
can you confirm the problem is fixed with current bashbot.sh?

**Comment by Azat868** [comment]
I need more time for tests

**Comment by gnadelwartz** [comment]
since I can not reproduce the Problem with the current Version i'll close for now.
feel free to give an Update if the Problem remains
